services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: healthcare-app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: healthcare-db
    restart: always
    environment:
      - MYSQL_DATABASE=healthcare_db
      - MYSQL_ROOT_PASSWORD=1234567890
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: healthcare-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge


volumes:
  db_data:
